services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    environment:
      - ConnectionStrings__Database=Host=cleanarchitecture.db; Database=cleanarchitecture-db; Username=postgres; Password=postgres
      - MessageBroker__Host=amqp://cleanarchitecture.mq:5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
    ports:
      - 5000:8080
      - 5001:8081

  cleanarchitecture.db:
    image: postgres:latest
    container_name: Database
    environment:
      - POSTGRES_DB=cleanarchitecture-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5433:5433

  cleanarchitecture.mq:
    image: rabbitmq:4.0.3-management
    container_name: Queue
    hostname: cleanarchitecture-queue
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672